interface CreatePaymentLinkParams {
  policyId: string;
  productName: string;
  amountCOP: number;
  expiresInMinutes?: number;
}

// Wompi's Payment Links API has no "reference" create-parameter — the transaction's
// `reference` field is auto-generated by Wompi and unrelated to our policyId.
// `payment_link_id` is the reliable link back to the payment_links.id we created.
interface CreatePaymentLinkResult {
  checkoutUrl: string;
  paymentLinkId: string;
}

interface WompiWebhookEvent {
  event: string;
  data: {
    transaction: {
      id: string;
      reference: string;
      payment_link_id?: string;
      status: 'APPROVED' | 'DECLINED' | 'VOIDED' | 'ERROR';
      amount_in_cents: number;
      payment_method_type: string;
      created_at: string;
    };
  };
  timestamp: number;
  signature: {
    checksum: string;
    // Dotted field paths (e.g. "transaction.id") whose VALUES get concatenated to build
    // the checksum. Wompi's docs warn this set/order can vary per event — never hardcode
    // a fixed field list; always read this array to know what to concatenate.
    properties: string[];
  };
}

interface WompiTransactionResult {
  transactionId: string;
  reference: string;
  paymentLinkId: string | null;
  status: string;
  amountInCents: number;
  paymentMethod: string;
  createdAt: string;
}

export { CreatePaymentLinkParams, CreatePaymentLinkResult, WompiWebhookEvent, WompiTransactionResult };