import { InsuranceProduct } from './types';

export const PRODUCTS: InsuranceProduct[] = [
  {
    id: 'accidentes-personales',
    name: 'Accidentes personales',
    category: 'accidentes',
    insurer: 'MetLife',
    basePremium: 18000,
    url: 'https://www.colsubsidio.com/seguros/familiares/accidentes',
    coverages: ['Cobertura por accidentes', 'Gastos médicos', 'Indemnización diaria por hospitalización', 'Reembolso de gastos médicos'],
    eligibility: { minAge: 18, maxAge: 70 },
  },
  {
    id: 'accidentes-premium',
    name: 'Accidentes personales (premium)',
    category: 'accidentes',
    insurer: 'Chubb',
    basePremium: 28100,
    url: 'https://www.colsubsidio.com/seguros/familiares/accidentes',
    coverages: ['Cobertura ampliada por accidentes', 'Gastos médicos mayores', 'Indemnización diaria', 'Protección familiar'],
    eligibility: { minAge: 18, maxAge: 70 },
  },
  {
    id: 'vida',
    name: 'Seguro de vida',
    category: 'vida',
    insurer: 'Pan American Life',
    basePremium: 12000,
    url: 'https://www.colsubsidio.com/seguros/familiares/vida',
    coverages: ['Protección por fallecimiento', 'Cobertura familiar', 'Indemnización por incapacidad'],
    eligibility: { minAge: 18, maxAge: 65 },
  },
  {
    id: 'asistencias-multiples',
    name: 'Asistencias múltiples',
    category: 'asistencia',
    insurer: 'GEA',
    basePremium: 20000,
    url: 'https://www.colsubsidio.com/seguros/familiares/asistencias-multiples',
    coverages: ['Asistencia en el hogar', 'Asistencia vehículo', 'Asistencia jurídica telefónica', 'Orientación familiar'],
    eligibility: {},
  },
  {
    id: 'exequial',
    name: 'Exequial',
    category: 'asistencia',
    insurer: 'Grupo Recordar',
    basePremium: 26000,
    url: 'https://www.colsubsidio.com/seguros/familiares/exequial',
    coverages: ['Servicios exequiales', 'Traslado nacional', 'Apoyo funerario familiar'],
    eligibility: {},
  },
  {
    id: 'accidentes-exequial',
    name: 'Accidentes + Exequial',
    category: 'accidentes',
    insurer: 'Pan American Life',
    basePremium: 14000,
    url: 'https://www.colsubsidio.com/seguros/familiares/accidente-exequial',
    coverages: ['Cobertura por accidentes', 'Servicios exequiales', 'Protección familiar'],
    eligibility: {},
  },
  {
    id: 'vida-ahorro',
    name: 'Vida + Ahorro',
    category: 'vida',
    insurer: 'BMI',
    basePremium: 20000,
    url: 'https://www.colsubsidio.com/seguros/familiares/vida-ahorro',
    coverages: ['Protección por fallecimiento', 'Componente de ahorro', 'Cobertura por incapacidad'],
    eligibility: {},
  },
  {
    id: 'asistencias-medicas',
    name: 'Asistencias médicas familiares',
    category: 'asistencia',
    insurer: 'GEA',
    basePremium: 16800,
    url: 'https://www.colsubsidio.com/seguros/familiares/asistencias-medicas',
    coverages: ['Asistencia médica telefónica', 'Consultas virtuales', 'Descuentos en medicamentos', 'Orientación nutricional'],
    eligibility: { family: true },
  },
  {
    id: 'asistencia-veterinaria',
    name: 'Asistencia veterinaria',
    category: 'mascotas',
    insurer: 'GEA',
    basePremium: 14500,
    url: 'https://www.colsubsidio.com/seguros/mascotas/asistencia-veterinaria',
    coverages: ['Consulta veterinaria', 'Refuerzo de vacunación', 'Sala de urgencias por accidente', 'Búsqueda y localización de mascotas', 'Exámenes de laboratorio', 'Baño medicado', 'Servicio exequial'],
    eligibility: { pet: 'any' },
  },
  {
    id: 'medicina-prepagada-gatos',
    name: 'Medicina prepagada mascotas (gatos)',
    category: 'mascotas',
    insurer: 'VetPlus',
    basePremium: 81800,
    url: 'https://www.colsubsidio.com/seguros/mascotas/medicina-prepagada',
    coverages: ['Medicina prepagada para gatos', 'Consultas ilimitadas', 'Cirugías', 'Hospitalización', 'Exámenes diagnósticos'],
    eligibility: { pet: 'gato' },
  },
  {
    id: 'medicina-prepagada-perros',
    name: 'Medicina prepagada mascotas (perros)',
    category: 'mascotas',
    insurer: 'VetPlus',
    basePremium: 96600,
    url: 'https://www.colsubsidio.com/seguros/mascotas/medicina-prepagada',
    coverages: ['Medicina prepagada para perros', 'Consultas ilimitadas', 'Cirugías', 'Hospitalización', 'Exámenes diagnósticos'],
    eligibility: { pet: 'perro' },
  },
];